services:
  kybalion:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollama-kybalion:latest
    container_name: ollama-kybalion-frontend
    restart: always
    ports:
      - "6001:80"
    environment:
      - NODE_ENV=production
    networks:
      - kybalion-network

networks:
  kybalion-network:
    driver: bridge
